robot_sim_node:
  ros__parameters:
    MOVE_TOPIC: /robot/move
    TTS_TOPIC: /robot/tts
    WHISPER_TOPIC: /robot/whisper

task_executor_node:
  ros__parameters:
    TASKS_TOPIC: /task/input
    GUI_SENDER: False
    